# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b11099c87423f481de69efd714440ab0a1da346b041ef5229ff2664f4f3eef98fba0e0097bcf5259a125c100d44e99c96467ac0e41e7293791c05e4a7dd0dd9

test:
  secret_key_base: 70b57a35f0bddcab717e572743b92f5985564f2ea8d1d32a4a0657f473c9a38b0c4ce60ff391658e6a64a72cf3eb7abd69e0aab2b3faa404219c6d8f6e74bcf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
